### ISSUE TITLE
Bug dans seance-4.Rmd

### ISSUE THREAD

**Issue by tupuni** [ALVignoles/R-pour-archeologues#18]
Bug à résoudre dans les code snippets suivant: 

- [x] Liste de 1 à l'infini dans https://github.com/ALVignoles/R-pour-archeologues/blob/50654d160a8817d831c8ed24ea9c2618105ad256/seance-4.Rmd#L55-L64

- [x] Mismatch entre les valeurs et l'échelle de couleur et/ou forme `Warning : No shared levels found between `names(values)` of the manual scale and the data's [32mshape[38;5;232m values` dans https://github.com/ALVignoles/R-pour-archeologues/blob/50654d160a8817d831c8ed24ea9c2618105ad256/seance-4.Rmd#L166-L197

**Comment by ALVignoles** [comment]
1) bug résolu en enlevant le commentaire de la ligne 62

2) -affichage des numéros de carrés résolus en affichant les labels à l'intérieur du plan (x/y = +10 au lieu de -10); 
-j'ai aussi mis à jour la liste "shape.pal" pour laquelle une valeur ne correspondait pas aux levels de jdd$type. 
-concernant le mismatch, c'est normal car nous n'avons pas encore ajouté les enregistrements, ce qui est fait uniquement dans le snipet {r boucle exemple} ligne 216. L'idée de ce snipet est de créer un fond de plan sur lequel on pourra supperposer les points avec e "+" de ggplot

**Comment by tupuni** [comment]
Super mais je ne vois pas les changements dans seance-4.Rmd
Est-ce que tu as "poussé" tes changements dans le dépôt en ligne depuis ta machine?
